apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: axis-swgi-operator
rules:
  - apiGroups: ["swgi.io"]
    resources: ["swgideployments", "swgideployments/status", "swgideployments/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
