apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swgi-openshift.fullname" . }}
type: Opaque
stringData:
  ADMIN_API_TOKEN: {{ .Values.secrets.adminApiToken | quote }}
  VIEWER_API_TOKEN: {{ .Values.secrets.viewerApiToken | quote }}
  signing_key_ed25519.pem: |
{{ .Values.secrets.signingKey | indent 4 }}
