/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OperatorEventsRouteImport } from './routes/operator-events'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorEventsRoute = OperatorEventsRouteImport.update({
  id: '/operator-events',
  path: '/operator-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/clusters': typeof ClustersRoute
  '/executions': typeof ExecutionsRoute
  '/operator-events': typeof OperatorEventsRoute
  '/organizations': typeof OrganizationsRoute
  '/policies': typeof PoliciesRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/clusters': typeof ClustersRoute
  '/executions': typeof ExecutionsRoute
  '/operator-events': typeof OperatorEventsRoute
  '/organizations': typeof OrganizationsRoute
  '/policies': typeof PoliciesRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/clusters': typeof ClustersRoute
  '/executions': typeof ExecutionsRoute
  '/operator-events': typeof OperatorEventsRoute
  '/organizations': typeof OrganizationsRoute
  '/policies': typeof PoliciesRoute
  '/receipts': typeof ReceiptsRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/clusters'
    | '/executions'
    | '/operator-events'
    | '/organizations'
    | '/policies'
    | '/receipts'
    | '/settings'
    | '/usage'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/clusters'
    | '/executions'
    | '/operator-events'
    | '/organizations'
    | '/policies'
    | '/receipts'
    | '/settings'
    | '/usage'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/clusters'
    | '/executions'
    | '/operator-events'
    | '/organizations'
    | '/policies'
    | '/receipts'
    | '/settings'
    | '/usage'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuditLogsRoute: typeof AuditLogsRoute
  ClustersRoute: typeof ClustersRoute
  ExecutionsRoute: typeof ExecutionsRoute
  OperatorEventsRoute: typeof OperatorEventsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PoliciesRoute: typeof PoliciesRoute
  ReceiptsRoute: typeof ReceiptsRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-events': {
      id: '/operator-events'
      path: '/operator-events'
      fullPath: '/operator-events'
      preLoaderRoute: typeof OperatorEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuditLogsRoute: AuditLogsRoute,
  ClustersRoute: ClustersRoute,
  ExecutionsRoute: ExecutionsRoute,
  OperatorEventsRoute: OperatorEventsRoute,
  OrganizationsRoute: OrganizationsRoute,
  PoliciesRoute: PoliciesRoute,
  ReceiptsRoute: ReceiptsRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
